name: "Release"

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        machine: [qemux86-64]

    env:
      BRANCH: master

    container:
      image: threexc/yocto-builder:latest
      env:
        WORKSPACE: /home/builder
      volumes:
        - ${{ github.workspace }}:/home/builder
      options: --privileged

    steps:
      - name: Prepare the container
        shell: bash
        run: |
          sudo sysctl fs.inotify.max_user_watches=524288
          sudo chown builder:users ${WORKSPACE}

      - name: Checkout required repositories
        shell: bash
        run: |
          echo Cloning OE Core
          git clone git://git.openembedded.org/openembedded-core oe-core
          cd oe-core
          git clone git://git.openembedded.org/bitbake bitbake
          git checkout hardknott
          cd bitbake
          git checkout 1.50
          echo
      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          path: meta-econ

      - name: Setup E-Con Linux environment
        shell: bash
        run: |
          source ${WORKSPACE}/oe-core/oe-init-build-env ${WORKSPACE}/build
          cat <<EOF >> conf/local.conf
          MACHINE = "${{ matrix.machine }}"
          INHERIT += "rm_work"
          BB_DISKMON_DIRS = ""
          BB_GIT_SHALLOW = "1"
          BB_GIT_SHALLOW_DEPTH = "1"
          BB_GENERATE_SHALLOW_TARBALLS = "1"
          EOF
          sed -i "s/buildstats//g" conf/local.conf
          bitbake-layers add-layer ${WORKSPACE}/meta-econ

      - name: Checking parsing of metadata
        shell: bash
        run: |
          source ${WORKSPACE}/oe-core/oe-init-build-env ${WORKSPACE}/build
          DISTRO="econ-tiny" bitbake econ-core-image
          DISTRO="econ" bitbake econ-core-image

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.ref }} ${{ steps.ver.outputs.ver }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Release E-Con Tiny Core
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          files: ${WORKSPACE}/build/tmp-musl/deploy/images/qemux86-64/*.rootfs.tar.bz2
            ${WORKSPACE}/build/tmp-glibc/deploy/images/qemux86-64/*.rootfs.tar.bz2
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

      - name: Upload Release E-Con Core
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          files: ${WORKSPACE}/build/tmp-glibc/deploy/images/qemux86-64/*.rootfs.tar.bz2
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
