name: "e-Con Linux Releases"


on:
  push:
    tags:
      - '*'


jobs:
  cleaner:
    runs-on: [self-hosted, Linux]
    steps:
      - name: Runner workspace path
        run: |
          echo "Cleaning up previous run"
          rm -rf "${{ github.workspace }}"

  build:
    runs-on: [self-hosted, Linux]
    timeout-minutes: 720

    strategy:
      matrix:
        machine: [qemux86-64]

    env:
      working-directory:

    steps:
      - name: Checkout required repositories
        shell: bash
        run: |
          echo Cloning OE Core
          git clone git://git.openembedded.org/openembedded-core oe-core
          cd oe-core
          git clone git://git.openembedded.org/bitbake bitbake
          git checkout hardknott
          cd bitbake
          git checkout 1.50
          echo

      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          path: meta-econ

      - name: Setup E-Con Linux environment
        shell: bash
        run: |
          source oe-core/oe-init-build-env build
          cat <<EOF >> conf/local.conf
          BB_NUMBER_THREADS = "4"
          PARALLEL_MAKE = "-j 4"
          do_fetch[number_threads] = "4"
          SSTATE_DIR = "/home/mofm/openembedded/sstate-cache"
          DL_DIR = "/home/mofm/openembedded/downloads"
          MACHINE = "${{ matrix.machine }}"
          INHERIT += "rm_work"
          EOF
          sed -i "s/buildstats//g" conf/local.conf
          bitbake-layers add-layer ../meta-econ

      - name: Building Images
        shell: bash
        run: |
          source oe-core/oe-init-build-env build
          DISTRO="econ-tiny" bitbake econ-core-image
          DISTRO="econ-tiny" bitbake econ-lighttpd
          DISTRO="econ" bitbake econ-core-image

      - name: Sign SHA256SUMS file
        shell: bash
        run: |
          gpg --sign ./build/SHA256SUMS

      - name: Release Notes
        uses: CSchoel/release-notes-from-changelog@v1
        with:
          working-directory: meta-econ

      - name: Show Release Notes
        run: cat meta-econ/RELEASE.md

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.ref }} ${{ steps.ver.outputs.ver }}
          tag_name: ${{ github.ref }}
          body_path: RELEASE.md # generated by release-notes-from-changelog
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Release E-Con Tiny Core
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/tmp-musl/deploy/images/qemux86-64/*qemux86-64.tar.xz
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

      - name: Upload Release E-Con Core
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/tmp-glibc/deploy/images/qemux86-64/*qemux86-64.tar.xz
          asset_name: 
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

      - name: Upload E-Con Tiny Core nspawn files
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/tmp-musl/deploy/images/qemux86-64/*.nspawn
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

      - name: Upload E-Con Core nspawn files
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/tmp-glibc/deploy/images/qemux86-64/*.nspawn
          asset_name: 
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

      - name: Upload SHA256SUMS files
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/SHA256SUMS*
          asset_name: 
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

