name: "Continuous Integration"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: [self-hosted, Linux]
    timeout-minutes: 720

    strategy:
      matrix:
        machine: [qemux86-64]

    env:
      WORKSPACE: /home/mofm/builder


    steps:
      - name: Checkout required repositories
        shell: bash
        run: |
          echo Cloning OE Core
          git clone git://git.openembedded.org/openembedded-core oe-core
          cd oe-core
          git clone git://git.openembedded.org/bitbake bitbake
          git checkout hardknott
          cd bitbake
          git checkout 1.50
          echo

      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          path: meta-econ

      - name: Setup E-Con Linux environment
        shell: bash
        run: |
          source ${WORKSPACE}/oe-core/oe-init-build-env ${WORKSPACE}/build
          cat <<EOF >> conf/local.conf
          SSTATE_DIR = "~/openembedded/sstate-cache"
          DL_DIR = "~/openembedded/downloads"
          MACHINE = "${{ matrix.machine }}"
          INHERIT += "rm_work"
          EOF
          sed -i "s/buildstats//g" conf/local.conf
          bitbake-layers add-layer ${WORKSPACE}/meta-econ

      - name: Checking parsing of metadata
        shell: bash
        run: |
          source ${WORKSPACE}/oe-core/oe-init-build-env ${WORKSPACE}/build
          DISTRO="econ-tiny" bitbake econ-core-image
          DISTRO="econ" bitbake econ-core-image

