name: "e-Con Linux CI"


on:
  push:
    branches:
      - main
  pull_request:


jobs:
  cleaner:
    runs-on: [self-hosted, Linux]
    steps:
      - name: Runner workspace path
        run: |
          echo "Cleaning up previous run"
          rm -rf "${{ github.workspace }}"

  build:
    runs-on: [self-hosted, Linux]
    timeout-minutes: 720

    strategy:
      matrix:
        machine: [qemux86-64]

    env:
      working-directory:

    steps:
      - name: Checkout required repositories
        shell: bash
        run: |
          echo Cloning OE Core
          git clone git://git.openembedded.org/openembedded-core oe-core
          cd oe-core
          git clone git://git.openembedded.org/bitbake bitbake
          git checkout hardknott
          cd bitbake
          git checkout 1.50
          echo

      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          path: meta-econ

      - name: Setup E-Con Linux environment
        shell: bash
        run: |
          source oe-core/oe-init-build-env build
          cat <<EOF >> conf/local.conf
          BB_NUMBER_THREADS = "4"
          PARALLEL_MAKE = "-j 4"
          do_fetch[number_threads] = "4"
          SSTATE_DIR = "/home/mofm/openembedded/sstate-cache"
          DL_DIR = "/home/mofm/openembedded/downloads"
          MACHINE = "${{ matrix.machine }}"
          INHERIT += "rm_work"
          EOF
          sed -i "s/buildstats//g" conf/local.conf
          bitbake-layers add-layer ../meta-econ

      - name: Building Images
        shell: bash
        run: |
          source oe-core/oe-init-build-env build
          DISTRO="econ-tiny" bitbake econ-core-image
          DISTRO="econ-tiny" bitbake econ-lighttpd
          DISTRO="econ" bitbake econ-core-image

